# automatically generated by the FlatBuffers compiler, do not modify

# namespace: response

import flatbuffers

class MatrixResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsMatrixResponse(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MatrixResponse()
        x.Init(buf, n + offset)
        return x

    # MatrixResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MatrixResponse
    def ResponseType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # MatrixResponse
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def MatrixResponseStart(builder): builder.StartObject(2)
def MatrixResponseAddResponseType(builder, responseType): builder.PrependUint8Slot(0, responseType, 0)
def MatrixResponseAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def MatrixResponseEnd(builder): return builder.EndObject()
