# automatically generated by the FlatBuffers compiler, do not modify

# namespace: request

import flatbuffers

class BivariateScalarRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsBivariateScalarRequest(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BivariateScalarRequest()
        x.Init(buf, n + offset)
        return x

    # BivariateScalarRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BivariateScalarRequest
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

    # BivariateScalarRequest
    def B(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def BivariateScalarRequestStart(builder): builder.StartObject(2)
def BivariateScalarRequestAddA(builder, a): builder.PrependFloat32Slot(0, a, 0.0)
def BivariateScalarRequestAddB(builder, b): builder.PrependFloat32Slot(1, b, 0.0)
def BivariateScalarRequestEnd(builder): return builder.EndObject()
